name: share_plus_example
description: Demonstrates how to use the share_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_logo.png

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'
