name: device_info_plus
description: Flutter plugin providing detailed information about the device
  (make, model, etc.), and Android or iOS version the app is running on.
version: 0.5.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.deviceinfo
        pluginClass: DeviceInfoPlugin
      ios:
        pluginClass: FLTDeviceInfoPlugin
      linux:
        default_package: device_info_plus_linux
      web:
        default_package: device_info_plus_web

dependencies:
  flutter:
    sdk: flutter
  device_info_plus_platform_interface: ^0.2.0
  device_info_plus_linux: ^0.1.0
  device_info_plus_web: ^0.2.0

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0<3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
