name: package_info_example
description: Demonstrates how to use the package_info_plus plugin.
version: 1.2.3+4
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  universal_io: ^2.0.4
  flutter:
    sdk: flutter
  package_info_plus:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
