# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Github Actions dependencies updates config
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Website dependencies updates config

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase

  # Android Alarm Manager dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/android_alarm_manager_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/android_alarm_manager_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/android_alarm_manager_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/android_alarm_manager_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Android Intent Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/android_intent_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/android_intent_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/android_intent_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/android_intent_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Battery Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/battery_plus/battery_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/battery_plus/battery_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/battery_plus/battery_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/battery_plus/battery_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "packages/battery_plus/battery_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Connectivity Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/connectivity_plus/connectivity_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/connectivity_plus/connectivity_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/connectivity_plus/connectivity_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/connectivity_plus/connectivity_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/connectivity_plus/connectivity_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Device Info Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/device_info_plus/device_info_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/device_info_plus/device_info_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/device_info_plus/device_info_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/device_info_plus/device_info_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/device_info_plus/device_info_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Network Info Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/network_info_plus/network_info_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/network_info_plus/network_info_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/network_info_plus/network_info_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/network_info_plus/network_info_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/network_info_plus/network_info_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Package Info Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/package_info_plus/package_info_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/package_info_plus/package_info_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/package_info_plus/package_info_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/package_info_plus/package_info_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/package_info_plus/package_info_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Sensors Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/sensors_plus/sensors_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/sensors_plus/sensors_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/sensors_plus/sensors_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/sensors_plus/sensors_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/sensors_plus/sensors_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Share Plus dependencies updates config

  - package-ecosystem: "pub"
    directory: "/packages/share_plus/share_plus"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/share_plus/share_plus/example"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/packages/share_plus/share_plus_platform_interface"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/packages/share_plus/share_plus/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gradle"
    directory: "/packages/share_plus/share_plus/example/android"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
