name: sensors_plus_platform_interface
description: A common platform interface for the sensors_plus plugin.
version: 1.1.2
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4"
