name: sensors_plus_platform_interface
description: A common platform interface for the sensors_plus plugin.
version: 1.1.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"
  test: ^1.22.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
