name: android_intent_plus
description: Flutter plugin for launching Android Intents. Not supported on iOS.
version: 5.3.0
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_intent_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_intent_plus
topics:
  - android
  - intent
  - utils

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.12.0
  mockito: ^5.4.0
  flutter_lints: ">=4.0.0 <7.0.0"
