name: android_intent_plus
description: Flutter plugin for launching Android Intents. Not supported on iOS.
version: 3.2.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_intent_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  mockito: ^5.0.0
  flutter_lints: ^1.0.4
