name: device_info_plus_macos
description: Macos implementation of the device_info_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 0.1.1

environment:
  sdk: ">=2.12.0-0"
  flutter: ">=1.20.0"

dependencies:
  device_info_plus_platform_interface: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DeviceInfoPlusMacosPlugin
