name: android_intent_plus
description: Flutter plugin for launching Android Intents. Not supported on iOS.
version: 1.0.0
homepage: https://github.com/fluttercommunity/android_intent_plus
documentation: https://github.com/fluttercommunity/android_intent_plus
maintainer: Miguel Beltran (@miquelbeltran)
authors:
  - Flutter Community <community@flutter.zone>
  - Miguel Beltran <m@beltran.work>

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.0.0
  meta: ^1.0.5
dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
