name: package_info_example
description: Demonstrates how to use the package_info_plus plugin.
dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
    path: ../
  integration_test: ^0.8.0
  universal_io: ^1.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
