name: battery_plus
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Android and iOS.
homepage: https://github.com/fluttercommunity/battery_plus
version: 1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.battery
        pluginClass: BatteryPlugin
      ios:
        pluginClass: FLTBatteryPlugin
      web:
        default_package: battery_plus_for_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  battery_plus_for_web:
    path: ../battery_plus_for_web

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.8.0
  plugin_platform_interface: ^1.0.0
  pedantic: ^1.9.0

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
