name: package_info_plus_macos
description: macOS implementation of the package_info_plus plugin.
version: 0.1.0
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FLTPackageInfoPlugin
        fileName: package_info_plus_macos.dart

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0