name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 4.0.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FLTSharePlusPlugin
      linux:
        default_package: share_plus_linux
      macos:
        default_package: share_plus_macos
      web:
        default_package: share_plus_web
      windows:
        default_package: share_plus_windows

dependencies:
  meta: ^1.7.0
  mime: ^1.0.0
  flutter:
    sdk: flutter
  share_plus_platform_interface: ^3.0.2
  share_plus_linux: ^3.0.0
  share_plus_macos: ^3.0.0
  share_plus_windows: ^3.0.0
  share_plus_web: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
