name: connectivity_plus
description: Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
version: 2.2.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: ConnectivityPlusPlugin
      linux:
        default_package: connectivity_plus_linux
      macos:
        default_package: connectivity_plus_macos
      web:
        default_package: connectivity_plus_web
      windows:
        default_package: connectivity_plus_windows

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus_platform_interface: ^1.2.0
  connectivity_plus_linux: ^1.2.0
  connectivity_plus_macos: ^1.2.0
  connectivity_plus_web: ^1.2.0
  connectivity_plus_windows: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^1.0.4
