name: connectivity_plus
description: Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
version: 2.3.9
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/connectivity_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: ConnectivityPlusPlugin
      linux:
        dartPluginClass: ConnectivityLinux
        pluginClass: none
      macos:
        default_package: connectivity_plus_macos
      web:
        default_package: connectivity_plus_web
      windows:
        default_package: connectivity_plus_windows

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus_platform_interface: ^1.2.0
  connectivity_plus_macos: ^1.2.4
  connectivity_plus_web: ^1.2.5
  connectivity_plus_windows: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  dbus: ^0.7.5
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
  test: ^1.21.1
