name: device_info_plus_platform_interface
description: A common platform interface for the device_info_plis plugin.
version: 0.3.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  plugin_platform_interface: ^1.1.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.2

environment:
  sdk: ">=2.12.0-0"
  flutter: ">=1.9.1+hotfix.4"
