name: share_plus_web
description: Web platform implementation of share_plus
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 3.1.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SharePlusPlugin
        fileName: share_plus_web.dart

dependencies:
  cross_file: ^0.3.3+2
  share_plus_platform_interface: ^3.0.2
  url_launcher: ^6.1.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.7.0
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
