name: battery_plus_example
description: Demonstrates how to use the battery_plus plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  battery_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:

dependency_overrides:
  args: ^2.0.0

flutter:
  uses-material-design: true
