name: battery_plus_example
description: Demonstrates how to use the battery_plus plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  battery_plus:
    path: ../

dependency_overrides:
  battery_plus_platform_interface:
    path: ../../battery_plus_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
