name: network_info_plus
description: Flutter plugin for discovering information (e.g. WiFi details) of the network.
version: 2.1.4
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.network_info
        pluginClass: NetworkInfoPlusPlugin
      ios:
        pluginClass: FLTNetworkInfoPlusPlugin
      linux:
        default_package: network_info_plus_linux
      macos:
        default_package: network_info_plus_macos
      windows:
        default_package: network_info_plus_windows
      web:
        default_package: network_info_plus_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  network_info_plus_platform_interface: ^1.1.2
  network_info_plus_linux: ^1.1.2
  network_info_plus_macos: ^1.3.0
  network_info_plus_windows: ^1.0.0
  network_info_plus_web: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  flutter_lints: ^1.0.4
