name: sensors_plus
description: Flutter plugin for accessing accelerometer, gyroscope, and
  magnetometer sensors.
version: 2.0.4
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/sensors_plus

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FLTSensorsPlusPlugin
      web:
        pluginClass: WebSensorsPlugin
        fileName: src/sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sensors_plus_platform_interface: ^1.1.3
dev_dependencies:
  test: ^1.16.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"
