name: sensors_plus
description: Flutter plugin for accessing accelerometer, gyroscope, and
  magnetometer sensors.
version: 6.1.0
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/sensors_plus/sensors_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/sensors_plus
topics:
  - sensor
  - sensors
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FPPSensorsPlusPlugin
      web:
        pluginClass: WebSensorsPlugin
        fileName: src/sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sensors_plus_platform_interface: ^2.0.0

dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
