name: sensors_plus
description: Flutter plugin for accessing accelerometer, gyroscope, and
  magnetometer sensors.
version: 4.0.2
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/sensors_plus/sensors_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/sensors_plus

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FPPSensorsPlusPlugin
      web:
        pluginClass: WebSensorsPlugin
        fileName: src/sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  sensors_plus_platform_interface: ^1.2.0
dev_dependencies:
  test: ^1.22.0
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
