name: package_info_plus
description: Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android.
version: 1.0.0-nullsafety.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.packageinfo
        pluginClass: PackageInfoPlugin
      ios:
        pluginClass: FLTPackageInfoPlusPlugin
      linux:
        default_package: package_info_plus_linux
      macos:
        default_package: package_info_plus_macos
      web:
        default_package: package_info_plus_web
      windows:
        default_package: package_info_plus_windows

dependencies:
  flutter:
    sdk: flutter
  package_info_plus_platform_interface: ^1.0.0-nullsafety
  package_info_plus_linux: ^1.0.0-nullsafety
  package_info_plus_macos: ^1.0.0-nullsafety
  package_info_plus_windows: ^1.0.0-nullsafety
  package_info_plus_web: ^1.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  pedantic: ^1.10.0

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5"
