name: battery_plus_example
description: Demonstrates how to use the battery_plus plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.2
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
