name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager_plus plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus:
    path: ../
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9

dev_dependencies:
  espresso: ^0.2.0+4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
