name: package_info_plus_linux
description: Linux implementation of the package_info_plus plugin
version: 1.0.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  package_info_plus_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
