name: sensors_plus_web
description: The web implementation of sensors_plus
version: 1.1.2
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SensorsPlugin
        fileName: sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_platform_interface: ^1.1.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  test: ^1.16.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
