name: connectivity_plus_web
description: An implementation for the web platform of the Flutter `connectivity_plus` plugin. This uses the NetworkInformation Web API, with a fallback to Navigator.onLine.
version: 1.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ConnectivityPlugin
        fileName: connectivity_plus_web.dart

dependencies:
  connectivity_plus_platform_interface: ^1.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
