name: connectivity_plus
description: Flutter plugin for discovering the state of the network (WiFi &
  mobile/cellular) connectivity on Android and iOS.
homepage: https://github.com/fluttercommunity/connectivity_plus
# 0.4.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.4.9+2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: FLTConnectivityPlugin
      macos:
        default_package: connectivity_plus_macos
      web:
        default_package: connectivity_plus_for_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  connectivity_plus_platform_interface: ^1.0.7
  connectivity_plus_macos: ^0.1.0+6
  connectivity_plus_for_web: ^0.3.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  integration_test: ^0.8.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
