name: share_plus_linux
description: Linux implementation of the share_plus plugin
version: 3.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  cross_file: ^0.3.3+2
  share_plus_platform_interface: ^3.0.2
  file: ^6.0.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  url_launcher_platform_interface: ^2.0.2

flutter:
  plugin:
    implements: share_plus
    platforms:
      linux:
        dartPluginClass: ShareLinux
        pluginClass: none
