name: battery_plus_linux
description: Linux implementation of the battery_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus_platform_interface: ^1.1.1
  dbus: ^0.6.6
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    implements: battery_plus
    platforms:
      linux:
        dartPluginClass: BatteryPlusLinux
        pluginClass: none
