name: battery_plus_linux
description: Linux implementation of the battery_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus_platform_interface: ^1.2.0
  meta: ^1.7.0
  upower: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  mockito: ^5.2.0

flutter:
  plugin:
    implements: battery_plus
    platforms:
      linux:
        dartPluginClass: BatteryPlusLinux
        pluginClass: none
