name: battery_plus
description: Flutter plugin for accessing information about the battery state(full, charging, discharging).
version: 2.1.4+1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/battery_plus

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.battery
        pluginClass: BatteryPlusPlugin
      ios:
        pluginClass: FLTBatteryPlusPlugin
      linux:
        default_package: battery_plus_linux
      macos:
        default_package: battery_plus_macos
      web:
        default_package: battery_plus_web
      windows:
        default_package: battery_plus_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  battery_plus_platform_interface: ^1.2.1
  battery_plus_linux: ^1.1.1
  battery_plus_macos: ^1.1.0
  battery_plus_web: ^1.1.0
  battery_plus_windows: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  async: ^2.8.2
  plugin_platform_interface: ^2.1.2
  test: ^1.16.4
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
