name: sensors_plus
description: Flutter plugin for accessing accelerometer and gyroscope sensors.
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/sensors_plus
version: 0.5.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sensors
        pluginClass: SensorsPlugin
      ios:
        pluginClass: FLTSensorsPlugin
      web:
        default_package: sensors_plus_web

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_web:
    path: ../sensors_plus_web
  sensors_plus_platform_interface:
    path: ../sensors_plus_platform_interface

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  mockito: ^4.1.1
  pedantic: ^1.8.0

environment:
  sdk: '>=2.1.0<3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
