name: share_plus_web
description: Web platform implementation of share_plus
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.1.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SharePlusPlugin
        fileName: share_plus_web.dart

dependencies:
  share_plus_platform_interface: ^1.2.0
  url_launcher: ^5.2.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  mockito: ^4.1.1
  integration_test: ^0.9.2

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.20.0"
