name: sensors_plus_example
description: Demonstrates how to use the sensors plugin.

dependencies:
  flutter:
    sdk: flutter
  sensors_plus:
    path: ../

dependency_overrides:
  sensors_plus_platform_interface:
    path: ../../sensors_plus_platform_interface
  sensors_plus_web:
    path: ../../sensors_plus_web

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.9.1+hotfix.2"
