name: sensors_example
description: Demonstrates how to use the sensors plugin.

dependencies:
  flutter:
    sdk: flutter
  sensors_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.9.1+hotfix.2"
