name: android_alarm_manager_plus
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 3.0.4
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_alarm_manager_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_alarm_manager_plus

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidalarmmanager
        pluginClass: AndroidAlarmManagerPlugin
