name: android_alarm_manager_plus
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 4.0.7
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_alarm_manager_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_alarm_manager_plus
topics:
  - android
  - alarm
  - utils

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidalarmmanager
        pluginClass: AndroidAlarmManagerPlugin
