name: share_plus_platform_interface
description: A common platform interface for the share_plus plugin.
version: 3.3.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  cross_file: ^0.3.3+4
  flutter:
    sdk: flutter
  meta: ^1.8.0
  mime: ^1.0.4
  plugin_platform_interface: ^2.1.4
  path_provider: ^2.0.14
  uuid: ">=3.0.7 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^2.0.1
  test: ^1.22.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
