name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus:
    path: ../

dependency_overrides:
  connectivity_plus_platform_interface:
    path: ../../connectivity_plus_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.16.4
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
