name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus plugin.

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.16.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
