name: network_info_plus_example
description: Demonstrates how to use the network_info_plus plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
