name: network_info_plus_example
description: Demonstrates how to use the network_info_plus plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^6.1.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  uses-material-design: true
