name: network_info_plus_example
description: Demonstrates how to use the network_info_plus plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.4
  integration_test:
  flutter_lints: ^1.0.4

dependency_overrides:
  args: ^2.0.0

flutter:
  uses-material-design: true
