name: package_info_plus_web
description: Web platform implementation of package_info_plus
version: 1.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PackageInfoPlugin
        fileName: package_info_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  meta: ^1.3.0
  package_info_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  build_runner: ^2.0.3
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
