name: battery_plus_web
description: An implementation for the web platform of the Flutter `battery_plus` plugin.
version: 0.4.0-nullsafety.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BatteryPlusPlugin
        fileName: battery_plus_web.dart

dependencies:
  battery_plus_platform_interface: ^0.4.0-nullsafety
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: '>=1.20.0'
