name: sensors_plus_platform_interface
description: A common platform interface for the sensors_plus plugin.
version: 1.0.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^1.1.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  test: ^1.16.2

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
  flutter: ">=1.9.1+hotfix.4"
