name: network_info_plus_platform_interface
description: A common platform interface for the network_info_plus plugin.
version: 1.1.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.4 <3.0.0"
