name: share_plus_platform_interface
description: A common platform interface for the share_plus plugin.
version: 2.0.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  mime: ^1.0.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.10.0
  test: ^1.16.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
