name: network_info_plus_linux
description: Linux implementation of the network_info_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  network_info_plus_platform_interface: ^1.1.0
  nm: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: NetworkInfoLinux
        pluginClass: none
