name: device_info_plus_example
description: Demonstrates how to use the device_info_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info_plus:
    path: ../../device_info_plus

dependency_overrides:
  device_info_plus_platform_interface:
    path: ../../device_info_plus_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

environment:
  sdk: '>=3.0.0-397.0.dev <4.0.0'
