name: device_info_plus_example
description: Demonstrates how to use the device_info_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

flutter:
  uses-material-design: true

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'


