name: device_info_example
description: Demonstrates how to use the device_info_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
