name: package_info_example
description: Demonstrates how to use the package_info_plus plugin.
version: 1.2.3+4
publish_to: 'none'

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
    path: ../
  integration_test: ^1.0.2
  universal_io: ^1.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
