name: battery_plus
description: Flutter plugin for accessing information about the battery state(full, charging, discharging) on Android and iOS.
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/battery_plus
version: 0.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.battery
        pluginClass: BatteryPlugin
      ios:
        pluginClass: FLTBatteryPlugin
      web:
        default_package: battery_plus_web
      windows:
        default_package: battery_plus_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  battery_plus_platform_interface: ^0.1.0
  battery_plus_web: ^0.1.0
  battery_plus_windows: ^0.1.0

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  plugin_platform_interface: ^1.0.0
  pedantic: ^1.9.0

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
