name: all_plugins

concurrency:
  group: all_plugins_${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"

jobs:
  analyze:
    name: "Flutter Analyze"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Run Dart Analyze"
        uses: invertase/github-action-dart-analyzer@v2.0.0
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          working-directory: ./packages

  pub_dev_publish_check:
    name: "Check pub.dev requirements"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Pub Check"
        run: |
          melos exec -c 1 --no-private --ignore="*example*" -- \
            flutter pub publish --dry-run

  pub_get_check:
    name: "Check pub dependencies"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Flutter Pub Get"
        run: |
          melos exec -c 1 --scope="*example*" -- \
            "flutter pub get"

  check_formatting:
    name: "Check code formatting"
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          curl -sL https://github.com/google/google-java-format/releases/download/google-java-format-1.3/google-java-format-1.3-all-deps.jar -o $HOME/google-java-format.jar
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Validate Dart formatting"
        run: |
          melos exec -c 1 -- \
            "dart format ."
          ./.github/workflows/scripts/validate-formatting.sh
      - name: "Validate Objective-C formatting"
        if: ${{ success() || failure() }}
        run: |
          melos exec -c 4 --ignore="*platform_interface*" --ignore="*web*" -- \
            find . -maxdepth 3 -name "*.h" -o -name "*.m" -print0 \| xargs -0 clang-format -i --verbose
          ./.github/workflows/scripts/validate-formatting.sh
      - name: "Validate Java formatting"
        if: ${{ success() || failure() }}
        run: |
          melos exec -c 4 --ignore="*platform_interface*" --ignore="*web*" -- \
            find . -maxdepth 12 -name "*.java" -print0 \| xargs -0 java -jar $HOME/google-java-format.jar --replace
          ./.github/workflows/scripts/validate-formatting.sh

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable

      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      - name: "Bootstrap Workspace"
        run: melos bootstrap

      - name: "Flutter Test"
        run: melos run test --no-select

      - name: "Flutter Test - Web"
        run: melos run test:web --no-select

