name: all_plugins

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install Flutter'
        uses: subosito/flutter-action@refs/pull/79/head
      - name: 'Install Tools'
        run: |
          flutter pub global activate melos
          flutter pub global activate tuneup
      - name: 'Bootstrap Workspace'
        run: melos bootstrap
      - name: 'Dart Analyze'
        run: |
          melos run analyze
      - name: 'Pub Check'
        run: |
          melos run lint:pub

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install Flutter'
        uses: subosito/flutter-action@refs/pull/79/head
      - name: 'Install Tools'
        run: |
          sudo apt update
          sudo apt install -y clang-format
          pub global activate melos
          pub global activate flutter_plugin_tools
      - name: 'Bootstrap Workspace'
        run: melos bootstrap
      - name: 'Melos Format'
        run: melos run format
      - name: 'Validate Formatting'
        run: |
          ./.github/workflows/scripts/validate-formatting.sh

  build_examples_dart:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install Flutter'
        uses: subosito/flutter-action@refs/pull/79/head
      - name: 'Install Tools'
        run: flutter pub global activate melos
      - name: 'Bootstrap Workspace'
        run: melos bootstrap
      - name: 'Build Example Snapshots'
        run: |
          melos run build:examples:bundle

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install Flutter'
        uses: subosito/flutter-action@refs/pull/79/head
      - name: 'Install Tools'
        run: flutter pub global activate melos
      - name: 'Bootstrap Workspace'
        run: melos bootstrap
      - name: 'Flutter Test'
        run: |
          melos run test
        if: matrix.os != 'ubuntu-latest'
      - name: 'Collect Coverage'
        run: |
          melos run coverage
        if: matrix.os == 'ubuntu-latest'
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: packages/*/coverage/lcov.info
        if: matrix.os == 'ubuntu-latest'

  integration_tests:
    if: false # currently broken, see issue 220
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Install Flutter'
        uses: subosito/flutter-action@refs/pull/79/head
        with:
          channel: dev
      - name: 'Install Tools'
        run: |
          flutter pub global activate melos
          flutter config --enable-linux-desktop
      - name: 'Setup Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake dbus libblkid-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb clang-format
          sudo apt install -y network-manager upower
        if: matrix.os == 'ubuntu-latest'
      - name: 'Bootstrap Workspace'
        run: melos bootstrap
      - name: 'Flutter Integration Test'
        run: |
          melos run test:e2e:linux
        if: matrix.os == 'ubuntu-latest'
