# Build Android Intent Plus Example
name: android_intent_plus

concurrency:
  group: android_intent_plus_${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/android_intent_plus/**"
      - ".github/workflows/android_intent_plus.yaml"
      - "!**.md"
      - "!**.gitignore"

env:
  PLUGIN_SCOPE: "*android_intent_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*android_intent_example*"

jobs:
  android_example_build:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart

  android_integration_test:
    runs-on: macos-13
    timeout-minutes: 30
    strategy:
      matrix:
        android-api-level: [ 22, 26, 31 ]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      - name: "Bootstrap Workspace"
        run: melos bootstrap --scope="$PLUGIN_SCOPE"

      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          cores: 3
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          profile: Nexus 5X
          script: ./.github/workflows/scripts/integration-test.sh android android_intent_example
