# Build Android Alarm Manager Plus Example
name: android_alarm_manager_plus

concurrency:
  group: android_alarm_manager_plus_${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/android_alarm_manager_plus/**"
      - ".github/workflows/android_alarm_manager_plus.yaml"
      - "!**.md"
      - "!**.gitignore"

env:
  PLUGIN_SCOPE: "*android_alarm_manager_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*android_alarm_manager_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

          # Required for Android builds
      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart

  android_integration_test:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        android-api-level: [21, 26, 32]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

          # Required for Android builds
      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          cores: 3
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          profile: Nexus 5X
          script: ./.github/workflows/scripts/integration-test.sh android android_alarm_manager_example
