# Build Connectivity Info Plus Example
name: connectivity_plus

on:
  pull_request:
    paths:
      - "packages/connectivity_plus/**"
      - ".github/workflows/connectivity_plus.yaml"
      - "!**.md"
      - "!**.gitignore"

env:
  PLUGIN_SCOPE: "*connectivity_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*connectivity_plus_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      # Required for Android builds
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart

  android_integration_test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      # Required for Android builds
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Nexus 5X
          script: ./.github/workflows/scripts/integration-test.sh android connectivity_plus_example

  ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh ios ./lib/main.dart

  ios_integration_test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Start Simulator"
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 8'
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh ios connectivity_plus_example

  macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh macos ./lib/main.dart

    macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh macos connectivity_plus_example

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh linux ./lib/main.dart

  windows:
    if: false # Disabled until Windows CI scripts are done
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh windows ./lib/main.dart

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh web ./lib/main.dart
