# Build Package Info Plus Example
name: package_info_plus

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.gitignore"
    paths:
      - "packages/package_info_plus/**"
      - ".github/workflows/package_info_plus.yaml"

env:
  PLUGIN_SCOPE: "*package_info_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*package_info_plus_example*"

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart

  ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh ios ./lib/main.dart

  macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh macos ./lib/main.dart

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh linux ./lib/main.dart

  windows:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh windows ./lib/main.dart

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh web ./lib/main.dart
